Invoke-WebRequest 'https://celestrak.org/NORAD/elements/gp.php?GROUP=weather&FORMAT=TLE' -OutFile kepler\weather\weather.txt;
Start-Sleep -Seconds 7;
Invoke-WebRequest 'https://celestrak.org/NORAD/elements/gp.php?GROUP=active&FORMAT=TLE' -OutFile kepler\active\active.txt;
Start-Sleep -Seconds 7;
Invoke-WebRequest 'https://celestrak.org/NORAD/elements/gp.php?GROUP=satnogs&FORMAT=TLE' -OutFile kepler\satnogs\satnogs.txt;
Start-Sleep -Seconds 7;
Invoke-WebRequest 'https://celestrak.org/NORAD/elements/gp.php?GROUP=visual&FORMAT=TLE' -OutFile kepler\visual\visual.txt;
Start-Sleep -Seconds 7;
Invoke-WebRequest 'https://celestrak.org/NORAD/elements/gp.php?GROUP=geo&FORMAT=TLE' -OutFile kepler\geo\geo.txt;
Start-Sleep -Seconds 7;
Invoke-WebRequest 'https://celestrak.org/NORAD/elements/gp.php?GROUP=amateur&FORMAT=TLE' -OutFile kepler\amateur\amateur.txt;
Start-Sleep -Seconds 7;
